### ISSUE TITLE
Add "immutabilization"projections to LaTeX documentation

### ISSUE THREAD

**Issue by tdv42** [polystat/py2eo#14]
https://www.overleaf.com/project/6177d231ad16318fb519b0de

**Comment by dours** [comment]
Full immutabilization projections are overly complicated (because changing a field in an object, which is referenced by other object, which are, in turn, referenced by other objects leads (in general) to a search in a reference graph, which is too much for just one simple assignment). 

So implementation of full immutabilizaton projection is, at least, temporarily, stopped.
